### PR TITLE
Separated engine concerns from game files

### PR DESCRIPTION
**Pull request by J-Mo63**
I've started doing the preliminary work in separating concerns of engine concepts from game definition. At this point, I've left tools as a part of the game definition but that's something we can think about adding to the engine later if we find it's useful to share. Not everything needs to happen in this PR - just throwing up ideas here for later reference.

I've also compiled some notes and thoughts on what should be part of the engine with regard to changes:

### Entity owns:
- GenerationalIndex
- transform&
- name&

### Engine parts:
- Components (structs)
    - Transform
    - Render2D
    - Render3D
    - Collider
- Systems
    - Entity (runs OnStart & OnUpdate, holds vector of Entity* and other bookkeeping info)
    - Render (holds vectors of Render2D &  Render3D objects)
    - Collision (holds vector of Collider objects that can be enabled and disabled)
- Other
    - Macros
    - Logging
    - Scene (Manager + Serialiser)
    - ServiceLocatorUtils
    - StringHelpers

## Misc questions
- Entity created inside the entity system, using std::forward??
- Is z-index an entity, transform, or render property - how to do sorting?
- Who owns bounding box - collision?
- Include engine-level entities?
- Static build engine before game?

### CODE REVIEW

**Review by Raelr — APPROVED** [review]
LGTM - I think that if we REALLY want to separate the engine out then we should actually move it to a separate project and build it as a library. The game would then be `a-dark-discomfort`, and the engine would be an API that the game uses. This seems to be a fairly common design pattern for these things. 

In fact, I was thinking that we could handle the overhaul to the entity system in a similar way - create a separate repo for it where we can encapsulate the basic API and unit tests and then build it as a library. Once it's done, we can then pull it into the main engine. 

I just had one comment on some formatting, but otherwise this looks fine to me.

**Comment by J-Mo63** [comment]
> LGTM - I think that if we REALLY want to separate the engine out then we should actually move it to a separate project and build it as a library. The game would then be `a-dark-discomfort`, and the engine would be an API that the game uses. This seems to be a fairly common design pattern for these things.
> 
> In fact, I was thinking that we could handle the overhaul to the entity system in a similar way - create a separate repo for it where we can encapsulate the basic API and unit tests and then build it as a library. Once it's done, we can then pull it into the main engine.

I think there's a halfway step here that we can entertain. While we're still making big changes to the engine API, I wouldn't put it into another repo because that would be a huge pain to manage changes and iterate on quickly. I was thinking that we can however throw the engine files into a separate directory which we build into a static lib, so when we do move it into a submodule, it's seamless.

**Comment by Raelr** [comment]
> 
> 
> > LGTM - I think that if we REALLY want to separate the engine out then we should actually move it to a separate project and build it as a library. The game would then be `a-dark-discomfort`, and the engine would be an API that the game uses. This seems to be a fairly common design pattern for these things.
> > In fact, I was thinking that we could handle the overhaul to the entity system in a similar way - create a separate repo for it where we can encapsulate the basic API and unit tests and then build it as a library. Once it's done, we can then pull it into the main engine.
> 
> I think there's a halfway step here that we can entertain. While we're still making big changes to the engine API, I wouldn't put it into another repo because that would be a huge pain to manage changes and iterate on quickly. I was thinking that we can however throw the engine files into a separate directory which we build into a static lib, so when we do move it into a submodule, it's seamless.

This can work as well. I guess as long as we have a way to differentiate between our game and engine logic then we should be fine.

**Comment by J-Mo63** [comment]
@Raelr so the question is, should we make the changes for the static build here, or merge this and do it in another PR?

**Comment by Raelr** [comment]
@J-Mo63 - let's merge this in for now and we can make the rest of the changes in a separate PR.

**Review by Raelr — APPROVED** [review]
LGTM 👍 : Approved

**Pull request merged**
